### ISSUE TITLE
】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by pukutan2021** [pukutan2021/protospace-36257#1]
https://git.heroku.com/protospace-36257.git

**Comment by takumi0530** [comment]
@pukutan2021 さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認のため、**本番環境のProtospaceのURL**をご提出いただければと思います。
（現在ご提出いただいておりますのは、GithubのURLとなります。）

提出方法に関しましてご不明点がある場合は、該当カリキュラム、またはテックコネクトにてご相談ください。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by pukutan2021** [comment]
https://protospace-36257.herokuapp.com/

よろしくお願い致します。

**Comment by takumi0530** [comment]
@pukutan2021 さん、再度ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
コメントに付随するユーザー名をクリックすると、書き込んだプロトタイプの投稿者のユーザー詳細ページに遷移してしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by pukutan2021** [comment]
https://git.heroku.com/protospace-36257.git

よろしくお願い致します。

**Comment by takumi0530** [comment]
@pukutan2021 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by pukutan2021** [comment]
ありがとうございました！
